### ISSUE TITLE
Spotify not showing

### ISSUE THREAD

**Issue by Ashik-Shaju** [waaverecords/PowerToys-Run-Spotify#1]
Spotify is not showing  under Power run section after copying extracted contet in designated directory.....so can't set client id

**Comment by waaverecords** [comment]
Have you tried restarting PowerToys after the extraction?

**Comment by Ashik-Shaju** [comment]
Yeah! several times...even restarted whole system

**Comment by waaverecords** [comment]
Once extracted the folder structure should look like this.

`C:\Program Files\PowerToys\RunPlugins`
`C:\Program Files\PowerToys\RunPlugins\PowerToys-Run-Spotify`

Then all the necessary dlls should be under that folder. Eg:

`C:\Program Files\PowerToys\RunPlugins\PowerToys-Run-Spotify\EmbedIO.dll`
`C:\Program Files\PowerToys\RunPlugins\PowerToys-Run-Spotify\SpotifyAPI.Web.dll`
`C:\Program Files\PowerToys\RunPlugins\PowerToys-Run-Spotify\...`

If you have the proper folder structure already.

Then the only thing that comes to mind is that you might have an outdated PowerToys version.
Prior to 0.77.0, this plugin won't work.
In that case, update your PowerToys then it should work.

**Comment by Ashik-Shaju** [comment]
I'm using latest version and tried everything multiple times, is anything else other than copying those files?like activation or installing anything or enabling anything to show Spotify under available plugins?

**Comment by AlejandroSuero** [comment]
I have the same problem, I am using the latest PowerToys version too.

![sp-not-working](https://github.com/waaverecords/PowerToys-Run-Spotify/assets/71392160/7086a26f-b0d0-436e-ad72-4326ae32ff4b)

Seems like it won't activate no matter if PowerToys is restarted either.

**Comment by waaverecords** [comment]
Mind looking into logs?
Search for `Spotify` keyword.

Logs should be located at.
`%LocalAppData%\Microsoft\PowerToys\PowerToys Run\Logs`

**Comment by Ashik-Shaju** [comment]
For me it is actually working  now

I was able to enter client Id and Authorize account and it showed it is done
I reinstalled powertoys from Microsoft store and went through every installation process from scratch including pasting the extracted content in both plugins and run plugins folders.

It will take sometime to get into full functionality Regarding keyword and spacing...I initially felt it's not working....

We can search, play and add to queue songs...
I felt controlling like pause and next and previous is possible but that's not possible from what i know
 
Mainly it will only work in web player not in desktop version 

Anyway a useful and great work from developer 
![IMG_20240118_023416](https://github.com/waaverecords/PowerToys-Run-Spotify/assets/92156898/ce9fd251-3f70-4aec-acf1-7060605b1816)
![IMG_20240118_022640](https://github.com/waaverecords/PowerToys-Run-Spotify/assets/92156898/05cceb4d-2f54-4bce-a624-b0e8a9d92682)

**Comment by waaverecords** [comment]
@Ashik-Shaju 

This is using [SpotifyAPI-NET](https://github.com/JohnnyCrazy/SpotifyAPI-NET) under the hood.
While fully controlling the player is not yet part of the plugin, more functionalities can be easily added.

Contributions are welcomed :)
