### ISSUE TITLE
Plugin failed to initialize

### ISSUE THREAD

**Issue by jteijema** [waaverecords/PowerToys-Run-Spotify#12]
Before upgrading to v0.78.0, the plugin failed to initialize. The warming message was non descriptive, only noting to contact the developer.

**Comment by jteijema** [comment]
Some info in the readme like #13 might help!

**Comment by waaverecords** [comment]
There is no control over what the warning message will be when an exception occurs.
The best thing that can be done is to look in logs to find what went wrong.

Usually at
`%LocalAppData%\Microsoft\PowerToys\PowerToys Run\Logs`
