### ISSUE TITLE
Documentation on update/upgrade process?

### ISSUE THREAD

**Issue by thegreenmilecornant** [waaverecords/PowerToys-Run-Spotify#15]
Hi!

Loving the plugin. Makes integrating with Spotify really slick throughout the workday. Thank you!

Just saw the new release 0.78.1. What is the best way of updating? Replace existing plugin folder? Are the settings for client id etc saved in another folder by PowerToys?

I guess a feature request would be to have an update-/upgrade-section in the readme for this?

**Comment by waaverecords** [comment]
You only need to replace the existing folder.
Any setting is saved elsewhere.

Great suggestion. I'll improve the documentation shortly.

**Comment by waaverecords** [comment]
Done.
