### ISSUE TITLE
With default 'sp' shortcut it is no longer possible to run spotify client

### ISSUE THREAD

**Issue by mmalolepszy** [waaverecords/PowerToys-Run-Spotify#17]
After installing the plugin it is no longer possible to run Spotify Windows client from PowerToys Run. 
![obraz](https://github.com/waaverecords/PowerToys-Run-Spotify/assets/9466870/601dffcb-058e-475a-ad4f-c326dca5aa0c)
I'd suggest changing the default shortcut to `sp:` or similar.

**Comment by waaverecords** [comment]
Upon selecting any action listed by the plugin, Spotify is opened if not open already.
You don't need to select Spotify directly anymore.

**Comment by mmalolepszy** [comment]
Well no, not always. I'm listening on a Spotify Connect enabled wireless speaker. I am able to control it via the plugin but the client does not start. But I guess it's not an usual use case, so probably not worth the hassle. I can live with manually changing the shortcut sequence.

**Comment by waaverecords** [comment]
You're right. I meant it opens Spotify if no active player is found.
Regardless, changing the keyword is the way to go.
