### ISSUE TITLE
Unable to activate

### ISSUE THREAD

**Issue by yu-ya-s** [waaverecords/PowerToys-Run-Spotify#19]
Please fix.
powertoys ver : v0.77.0

bug screen
![image](https://github.com/waaverecords/PowerToys-Run-Spotify/assets/65332126/3b46e2b2-733a-411c-b08c-28ee04dbbee6)

location
![image](https://github.com/waaverecords/PowerToys-Run-Spotify/assets/65332126/37815a93-9144-466c-975f-ab7882153cbb)

**Comment by waaverecords** [comment]
Make sure you use the related release for your PowerToys version v0.77.0.
https://github.com/waaverecords/PowerToys-Run-Spotify/releases/tag/v0.77.2

However, I'd recommend upgrading PowerToys to its latest version V0.79.0, and using the latest release of PowerToys-Run-Spotify to have all functionalities.
https://github.com/waaverecords/PowerToys-Run-Spotify/releases/tag/v0.79.0

**Comment by yu-ya-s** [comment]
Thanks!
I upgraded the PowerToys version and it worked.
