### ISSUE TITLE
How is it supposed to work?

### ISSUE THREAD

**Issue by AlejandroSuero** [waaverecords/PowerToys-Run-Spotify#2]
Now that the command is working, with the Spotify app or the Spotify player in the browser, neither of the songs adds to the queue nor do they play.

So my question is, how is it supposed to work exactly?

I have Premium so that shouldn't be the problem according to the [README.md](https://github.com/waaverecords/PowerToys-Run-Spotify/blob/main/README.md)

At the right is the Spotify app and at the left side is browser player, neither of them are playing or adding to the queue

![sp-not-working](https://github.com/waaverecords/PowerToys-Run-Spotify/assets/71392160/f7bd8928-b1d5-4171-9814-935662063a6a)

**Comment by matheustenedini** [comment]
Same here.

I get the following error:
```
-------------------------- Begin exception --------------------------
Message: Exception for plugin <Spotify> when query <sp>

Exception full name  : System.ArgumentException
Exception message    : String is empty or null (Parameter 'query')
Exception stack trace:
   at SpotifyAPI.Web.Ensure.ArgumentNotNullOrEmptyString(String value, String name)
   at SpotifyAPI.Web.SearchRequest..ctor(Types type, String query)
   at PowerToys_Run_Spotify.Main.Query(Query query) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 96
   at PowerLauncher.Plugin.PluginManager.<>c__DisplayClass23_0.<QueryForPlugin>b__0()
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action)
   at PowerLauncher.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query, Boolean delayedExecution)
Exception source     : SpotifyAPI.Web
Exception target site: Void ArgumentNotNullOrEmptyString(System.String, System.String)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------
```

**Comment by AlejandroSuero** [comment]
Right now is not showing result after typing `sp lofi` for example

**Comment by AfzalArfan** [comment]
same issue it doesn't play or does any thing just view everything but doesn't work.

**Comment by waaverecords** [comment]
Working on it.
It has to do with what the Spotify API deems the active device.

**Comment by waaverecords** [comment]
Commit ea1e5cb ensures there is an active device on each player control request.
If no active device is found, the Spotify application is opened, deeming your computer as active device, 

This is will be in the next release.

Thanks for your input on the plugin 🙏

**Comment by waaverecords** [comment]
https://github.com/waaverecords/PowerToys-Run-Spotify/releases/tag/v0.77.1

**Comment by waaverecords** [comment]
Release addressing this.

https://github.com/waaverecords/PowerToys-Run-Spotify/releases/tag/v0.77.1

**Comment by AfzalArfan** [comment]
how is it supposed to work as soon as i hit enter nothing happens no player appears nothing happens just few seconds of loading and nothing happens.

________________________________
