### ISSUE TITLE
Plugin spotify failed to load in Powertoys, not showing the clientID input.

### ISSUE THREAD

**Issue by shawny43** [waaverecords/PowerToys-Run-Spotify#20]
ClientID input are missing because Powertoys are in error.

**Comment by waaverecords** [comment]
More info needed.
- PowerToys-Run-Spotify version
- PowerToys version

Usually, when something is not working, it's a matter of mismatch versions.

See https://github.com/waaverecords/PowerToys-Run-Spotify/issues/19#issuecomment-1983382125

**Comment by shawny43** [comment]
Powertoys 0.78.0 (Preview)
Run : 0.79.0

I guess i figure out what's wrong.

**Comment by RickeyWard** [comment]
I had this same issue where the Client ID input disappears even though auth is not successful. Have to disable spotify plugin and restart, then reenable it, the client ID field comes back.
