### ISSUE TITLE
Powertoys failed to load the plugin

### ISSUE THREAD

**Issue by Asendaweth** [waaverecords/PowerToys-Run-Spotify#22]
I am trying to install the Spotify plugins and I have tried extracting the Zip files to both locations mentioned in the .zip file but Power Toys is still failing to load the plugin

![image](https://github.com/waaverecords/PowerToys-Run-Spotify/assets/80320487/9eb2f555-d4b2-4372-97f7-71cabe577843)

**Comment by waaverecords** [comment]
Can you look into the PowerToys logs to see what's going on?
Usually at
%LocalAppData%\Microsoft\PowerToys\PowerToys Run\Logs



Make sure your PowerToys version is v0.80.1 and that your PowerToys-Run-Spotify version is also [v0.80.1](https://github.com/waaverecords/PowerToys-Run-Spotify/releases/tag/v0.80.1).

**Comment by Asendaweth** [comment]
yup powertoys was the wrong version, works like a charm now. Thanks!
