### ISSUE TITLE
Searching through Your library?

### ISSUE THREAD

**Issue by jeregon1** [waaverecords/PowerToys-Run-Spotify#27]
So, sometimes (most of the times) I want a playlist I created myself, and I think that doesn't happen in this plugin.

I think what happens is that it searches across all the elements in Spotify's public resources, and so it is a worse search than just looking in the Library itself, because many other instances are found.

So it would be nice to narrow down the search to your library maybe with a special command like `sp l` or something like that.

We can talk too about searching filters (only songs, only playlists, etc.), but maybe that's for another Issue

**Comment by waaverecords** [comment]
Yeah, I would create another issue for scoping search to a specific item type.

As for your first point, this is somewhat related to https://github.com/waaverecords/PowerToys-Run-Spotify/issues/5 where nothing can be done for "liked songs".
However, for playlists the user owns, I believe this is achievable.

It would be done using `_spotifyClient.Playlists.GetUsers` and `_spotifyClient.Playlists.GetItems`.

You are welcome to validate this and submit a PR if it works.

**Comment by jeregon1** [comment]
Thank you!

I'm right up close to finishing the academic year and thus somewhat busy, and haven't used C#, but I'm certain Copilot has, so he'll be able to teach me.

**Comment by jeregon1** [comment]
Sorry guys, I'm switching to Flow launcher, no need to reinvent the wheel!
