### ISSUE TITLE
power tool. pop up at start up. 

### ISSUE THREAD

**Issue by Liferocka** [waaverecords/PowerToys-Run-Spotify#3]
Hi, Id like to run power tools at start-up, but, I dont want the "Whats New, in this version" to always Open when I start my computer. Can you tell me how to have it run but not pop up?

**Comment by waaverecords** [comment]
This is an issue regarding PowerToys itself, I think your question will be better answered there.

[PowerToys](https://github.com/microsoft/PowerToys)
