### ISSUE TITLE
Plugin Broken with PowerToys v0.82.0

### ISSUE THREAD

**Issue by lylebrown** [waaverecords/PowerToys-Run-Spotify#30]
Running on Windows 11, unable to enable the Spotify plugin after updating PowerToys to v0.82.0 (released on 7/2/2024).

**Comment by waaverecords** [comment]
Release for v0.82.0 has not been done yet.
Will do it sometime, tomorrow.

**Comment by waaverecords** [comment]
Here's the release https://github.com/waaverecords/PowerToys-Run-Spotify/releases/tag/v0.82.0.
