### ISSUE TITLE
Failed to Load plugin: P

### ISSUE THREAD

**Issue by 4bd1f002** [waaverecords/PowerToys-Run-Spotify#31]
Tried out the latest release, and I'm getting a failed to load message.

Tested in both plugin locations (no joy):

- %LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins
- C:\Program Files\PowerToys\RunPlugins

Running latest version of PT (v0.83.0)

![image](https://github.com/user-attachments/assets/a4d5c5d8-dd57-4c4c-9beb-9d560abf5f64)

**Comment by lylebrown** [comment]
@waaverecords what steps do you take to update the dll files when PowerToys has a new version?

I know you're pretty quick with this, but I don't mind trying to help out if I can understand the process.

**Comment by waaverecords** [comment]
Release for v0.83.0 has not been created yet.
Doing it right now.

**Comment by waaverecords** [comment]
Here's the release https://github.com/waaverecords/PowerToys-Run-Spotify/releases/tag/v0.83.0

**Comment by waaverecords** [comment]
> @waaverecords what steps do you take to update the dll files when PowerToys has a new version?
> 
> I know you're pretty quick with this, but I don't mind trying to help out if I can understand the process.

Very simple.

A few dlls found in the Power Toys installation folder are copied to the repo's folder.
A commit is then done, followed by a new release.

You can run `libs/ImportDlls.bat` to automatically copy the necessary dlls in the proper folder.
