### ISSUE TITLE
Updated to .84, not working

### ISSUE THREAD

**Issue by 4bd1f002** [waaverecords/PowerToys-Run-Spotify#32]
Since the update to 0.84.0, doesn't run.

**Comment by lisekilis** [comment]
can confirm
the plugin no longer works as of 0.84.0

**Comment by waaverecords** [comment]
Totally, normal.

Dlls needs to be updated on every new release of PowerToys.

Will do it later tonight.

**Comment by waaverecords** [comment]
https://github.com/waaverecords/PowerToys-Run-Spotify/releases/tag/v0.84.0
