### ISSUE TITLE
Failed to load, contact plugin creator for help

### ISSUE THREAD

**Issue by GeneralDhruv** [waaverecords/PowerToys-Run-Spotify#33]
When I placed the folder in the `%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins` directory and restart the PowerToys following all the  steps correctly, it shows the following error message:
![image](https://github.com/user-attachments/assets/024d1471-2f14-4732-9619-eeb7e222a6c5)

**Comment by waaverecords** [comment]
You may encounter this, because of mismatch version between PowerToys and PowerToys-Run-Spotify.
In that case, match your PowerToys version with PowerToys-Run-Spotify release.

**Comment by GeneralDhruv** [comment]
How can I verify if the versions for both of them match?
