### ISSUE TITLE
Error while initialising plugin

### ISSUE THREAD

**Issue by Dampfie93** [waaverecords/PowerToys-Run-Spotify#39]
Hi,
Spotify plugin installed. After running PowerToys its producing a "Error when initialising plug-ins: Spotify" and deactivates it.

Used latest release .zip file extracted as supposed to
Tryed to downgrade a version but same error.

Thougt its because of the Client-ID missing, but this options isnt even available in the options.
Using a german system language but in the option theres
 - set shortcut
 - include in global result (checkbox)
 - evaluation modifier (0 - 1000)

**Comment by waaverecords** [comment]
Can you look at the logs?

https://github.com/waaverecords/PowerToys-Run-Spotify/issues/1#issuecomment-1896684757

**Comment by flupkede** [comment]
Can't find class implement IPlugin for <Spotify> in C:\Program Files\PowerToys\RunPlugins\PowerToys-Run-Spotify\PowerToys-Run-Spotify.dll

Exception full name  : System.InvalidOperationException
Exception message    : Sequence contains no matching element
Exception stack trace:
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Wox.Plugin.PluginPair.CreatePluginInstance()
Exception source     : System.Linq
Exception target site: Void ThrowNoMatchException()
Exception HResult    : -2146233079

**Comment by waaverecords** [comment]
Is your PowerToys version the same as the plugin?
They need to match.

**Comment by Dampfie93** [comment]
> Is your PowerToys version the same as the plugin? They need to match.

Thanks, I was so sure my PowerToys wasn't out of date that I didn't even check. Sorry about the ticket
