### ISSUE TITLE
Failed to load, contact plugin creator for help (for PowerToys v86.0)

### ISSUE THREAD

**Issue by sinchxn** [waaverecords/PowerToys-Run-Spotify#41]
From what I understand, the dlls of the spotify plugin need to be updated to match the latest powertoys version? 
I know you're probably gonna roll out an update soon, but I don't mind trying to help keep it upto date if I know how the dlls change with each version!

**Comment by waaverecords** [comment]
Someone else has already submitted a PR with the updated DLLs.

The process is straightforward:

Run [ImportDlls.bat](https://github.com/waaverecords/PowerToys-Run-Spotify/blob/v0.86.0/ImportDlls.bat) to update the DLLs in the repository.
Then, use [BuildAndInstallPlugin.bat](https://github.com/waaverecords/PowerToys-Run-Spotify/blob/v0.86.0/BuildAndInstallPlugin.bat) to test the new version.

Thanks anyway!
