### ISSUE TITLE
Plugin not working after updating to PowerToys v0.87.0

### ISSUE THREAD

**Issue by GOD-OF-THE-GODS** [waaverecords/PowerToys-Run-Spotify#47]
I have recently updated to PowerToys v0.87.0 and the plug in stoped working it was working fine in the previous version but now everytime i open powertoys run it shows a message and doesn't work .

![Screenshot 2024-12-17 194132](https://github.com/user-attachments/assets/19e30ea4-9638-4f8a-8367-c49c2bcd34bf)

**Comment by jvherck** [comment]
+1

**Comment by waaverecords** [comment]
As expected.
The plugin needs to be updated on every release new PowerToys release.

I'll make the update tonight.

**Comment by waaverecords** [comment]
https://github.com/waaverecords/PowerToys-Run-Spotify/releases/tag/v0.87.0

**Comment by davidegiacometti** [comment]
Hey @waaverecords 

The PowerToys release usually shouldn't break the plugin.
Don't have Spotify Premium so I am not really able to test it but I have been able to load it in 0.87 after removing PowerToys dlls from the plugin folder:
- PowerToys.Common.Ul.dll
- PowerToys.ManagedCommon.dll
- PowerToys.Settings.Ul.Lib.dll
- Wox.Plugin.dll

```
[2024-12-17 22:27:05.9956] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::57]
Total initialize cost for <Spotify> is <3ms>
```

These dlls shouldn't be required/shipped within the plugin.
Just wanted to leave the feedback here.

**Comment by waaverecords** [comment]
They previously were required for the plugin to work.
Even Nuget packages used by standalone plugins wouldn't work a few PowerToys versions ago.

Awesome if this is no longer necessary

Thanks for letting me know. I'll look into it.

**Comment by benson1137** [comment]
> Hey @waaverecords
> 
> The PowerToys release usually shouldn't break the plugin. Don't have Spotify Premium so I am not really able to test it but I have been able to load it in 0.87 after removing PowerToys dlls from the plugin folder:
> 
> * PowerToys.Common.Ul.dll
> * PowerToys.ManagedCommon.dll
> * PowerToys.Settings.Ul.Lib.dll
> * Wox.Plugin.dll
> 
> ```
> [2024-12-17 22:27:05.9956] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::57]
> Total initialize cost for <Spotify> is <3ms>
> ```
> 
> These dlls shouldn't be required/shipped within the plugin. Just wanted to leave the feedback here.

It works ! Applause
