### ISSUE TITLE
Music plays on random device

### ISSUE THREAD

**Issue by jtchase08** [waaverecords/PowerToys-Run-Spotify#6]
Extension is installed and working, but when I choose music to play it doesn't play on my computer. Instead, Spotify connects to a random device on my network and plays from there instead.

**Comment by waaverecords** [comment]
Known.

Looking into what can be done, as this is more a Spotify API related issue.

**Comment by waaverecords** [comment]
Fixed with 5d4998a0a278b070e206e07207636ae134cb617d.

When no active device is found, after Spotify is opened, it will pick the device with the same name as `Environment.MachineName`.
