### ISSUE TITLE
Client ID section not appear

### ISSUE THREAD

**Issue by PedroBrantes** [waaverecords/PowerToys-Run-Spotify#7]
![image](https://github.com/waaverecords/PowerToys-Run-Spotify/assets/58346706/10681ee8-9ad4-45e2-9e14-c2631985fa6d)

**Comment by waaverecords** [comment]
This might be caused by the very recent PowerToys update (v0.77.2 to v0.78.0).
I've released a new version with updated dlls.

Here's the release.
https://github.com/waaverecords/PowerToys-Run-Spotify/releases/tag/v0.78.0

Let me know if this release fixes your issue.

**Comment by PedroBrantes** [comment]
> Let me know if this release fixes your issue.

It still doesn't show up

**Comment by PedroBrantes** [comment]
I downgraded to version 0.76.2 and it appeared, it's really a problem with version 0.78.0

**Comment by waaverecords** [comment]
It should work as long as you match your PowerToys version with this plugin's version.

**Comment by PedroBrantes** [comment]
> It should work as long as you match your PowerToys version with this plugin's version.

Just to let it recorded here, I updated to 0.79 along with the plugin and it's working normally
